### ISSUE TITLE
How do you set the bandwidth in Gaussian Kernel

### ISSUE THREAD

**Issue by Aixile** [lyttonhao/Neural-Style-MMD#4]
Hi, I wonder how do you set the bandwidth parameter of Gaussian Kernel here.
https://github.com/lyttonhao/Neural-Style-MMD/blob/master/mmd_loss.py#L65
Can you give me an explanation? Thank you!

**Comment by lyttonhao** [comment]
The bandwidth of Gaussian kernel is set as the average distances on the pairwise samples (median heuristic) according to some domain adaptation papers, such as [a]

[a] Long, Mingsheng, et al. "Learning transferable features with deep adaptation networks." International Conference on Machine Learning. 2015.

**Comment by Aixile** [comment]
Thanks for your explanation!
